name: device_trust
description: Heuristic device integrity signals for Flutter (root/jailbreak, emulator/simulator, Frida/hook, debugger) – Android & iOS.
version: 1.0.0
homepage: https://github.com/MuhammedErdemKazanci/device_trust
repository: https://github.com/MuhammedErdemKazanci/device_trust
issue_tracker: https://github.com/MuhammedErdemKazanci/device_trust/issues
documentation: https://github.com/MuhammedErdemKazanci/device_trust#readme
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - security
  - device-integrity
  - emulator-detection
  - jailbreak
  - frida

platforms:
  android:
  ios:

screenshots:
  - description: "iOS diagnostic UI - summary & policy"
    path: screenshots/ios-summary.png
  - description: "Android diagnostic UI - summary & policy"
    path: screenshots/android-summary.png

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mikoloy.device_trust
        pluginClass: DeviceTrustPlugin
      ios:
        pluginClass: DeviceTrustPlugin